flyway.url = jdbc:postgresql://taskbask-staging-psql.porter.in:5432/taskbask
flyway.schemas=application
flyway.locations = filesystem:servers/commons/src/main/db/migrations
flyway.outOfOrder = true
flyway.user = taskbask_owner
